tag:
  - code
task: mbpp_diffulex
dataset_path: json
dataset_name: null
dataset_kwargs:
  data_files: diffulex_bench/data/MBPP.json
test_split: train
output_type: generate_until
unsafe_code: true
doc_to_text: !function sdar_utils.doc_to_text_code_function
doc_to_target: "{{question}}"
process_results: !function sdar_utils.process_results_code
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "<|im_end|>"
    - "</s>"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 2048
repeats: 1
num_fewshot: 0
metadata:
  version: 1.0
  description: "MBPP Lightning JSON (diffulex)."
